---
collections:

# With the collection name, version, and source options
 - name: community.zabbix
   version: 1.2.0
#   source: 'The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)'
